version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    networks:
      - my-network
    volumes:
      - ./init-mongo-db-with-collections.js:/docker-entrypoint-initdb.d/init-mongo-db-with-collections.js:ro

  neuralnetwork:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: neuralnetwork
    image: neuralnetwork-image
    depends_on:
      - mongo
    networks:
      - my-network
    ports:
      - "8080:8080"
    restart: always

networks:
  my-network:
    driver: bridge